# Team names
teams:
  - "Aaron"
  - "Brett"
  - "Cobb"
  - "DiMaggio"
  - "Eckersley"
  - "Feller"

# Field names
fields:
  - "Little League Upper"
  - "Little League Lower"

# Week names (can be dates or descriptive names)
weeks:
  - Apr 6
  - Apr 13
  - Apr 20
  - Apr 27
  - May 4
  - May 11
  - May 18
  - May 25
  - Jun 1

# Game slots (time slots that exist for every field each week)
slots:
  - "Tue 6:00pm-8:00pm"
  - "Wed 6:00pm-8:00pm"
  - "Thu 6:00pm-8:00pm"
